### ISSUE TITLE
Getting stuck on lashed rope

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#375] opened 2022-03-29 16:49 UTC
1. Go east one map
2. Lash the bottom-right rope
3. Climb down it
4. You might get stuck when you try to get off.  If you press the arrow keys enough, you can guarantee that it will happen eventually.

I have tried to replicate twice, and it happened both times.
![image](https://user-images.githubusercontent.com/6566982/160663976-8e381dae-c2e6-4fb2-9805-ed102f20be16.png)
https://www.reddit.com/r/GoldenSun/comments/s09oyv/comment/i2kzw8h

**Comment by jjppof** [comment] 2022-03-29 17:25
Oh, that's a known one, many thanks anyway!

**Comment by jjppof** [comment] 2022-03-29 17:25
Duplicate of #362

**Closed** 2022-03-31 15:59 UTC
Labels: bug, duplicate
