### ISSUE TITLE
Cursed items are still equipped after the curse is removed

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#424] opened 2022-04-20 03:52 UTC
Cursed items are still equipped after the curse is removed.

**Comment by jjppof** [comment] 2022-04-20 12:28
Could not reproduce this one.
![curse](https://user-images.githubusercontent.com/7890647/164230242-e3c61a5f-9723-482b-97ad-816c8a3bbfb5.gif)

**Comment by MilesBHuff** [comment] 2022-04-20 23:12
Interesting.  It may be that this only happens after some other things have occurred -- I'll try to recreate.

**Comment by jjppof** [comment] 2022-04-21 02:30
I will close this one for now. The algorithm behind this feature is fair simple and deterministic... 99% sure this is working fine 😁

**Closed by jjppof** 2022-04-21 02:30 UTC
Labels: bug, could not reproduce
