### ISSUE TITLE
Tiles disappear when returning from other map following a battle

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#394] opened 2022-04-11 21:03 UTC
Unsure if reproducible, but reporting just in case.
There's nothing of interest in the console.
![image](https://user-images.githubusercontent.com/6566982/162831678-e5757952-9493-4249-9978-ec39c4577bdd.png)

**Comment by MilesBHuff** [comment] 2022-04-11 21:07
Didn't happen when leaving and re-entering.

**Comment by MilesBHuff** [comment] 2022-04-11 21:07
Leaving, fighting one more battle, and re-entering resulted in the same situation:
![image](https://user-images.githubusercontent.com/6566982/162832689-f66b62e8-7443-4633-8e31-8274d01fb2a6.png)

**Comment by jjppof** [comment] 2022-04-11 22:10
Duplicate of #297

**Closed by jjppof** 2022-04-11 22:10 UTC
